### ISSUE TITLE
resources packs vault.pkg and sponza.pkg

### ISSUE THREAD

**Issue by SunshineDou** [Siriuscoder/3dlite#69]
Hello, I have compiled the project successfully, but I cannot download the resources packs vault.pkg and sponza.pkg. is there something wrong with the link? Could you please give me a help?Thank you very much

**Comment by Siriuscoder** [comment]
Hello my frend! Sorry, i missed you question because i did not worked at the project a lot of time. You able to download pakcs from https://cloud.mail.ru/public/8eAZ/BAjJhjqYE and https://cloud.mail.ru/public/AJiq/HpapxfZCc , but if you have a problems i can upload its in other location. Now i am returning to developing.
